import { useEffect, useState } from 'react';
import { X } from 'lucide-react';

/*
 * Legal documents — Terms & Conditions and Privacy Policy.
 *
 *   <LegalModal document="terms" onClose={...} />
 *
 * The footer links switch between the two, so either can be opened first.
 * Text marked `strong` is highlighted, matching the design.
 */

export const LAST_UPDATED = 'September 2026';

const TERMS = {
  title: 'Terms & Conditions',
  intro:
    'Welcome to the SWUMed Queue Management System. By accessing or using this system, you agree to follow these Terms & Conditions. Please read them carefully before using the system.',
  sections: [
    {
      heading: '1. Purpose of the System',
      paragraphs: [
        'The SWUMed Queue Management System is designed to help manage and monitor patient queues within participating SWUMed hospital departments. The system supports queue generation, queue monitoring, patient calling, transaction tracking, and administrative management.',
      ],
    },
    {
      heading: '2. Authorized Access',
      paragraphs: [
        'Access to the administrative and staff features of the system is restricted to authorized SWUMed personnel.',
        'Users are responsible for:',
      ],
      list: [
        { text: 'Using only the account assigned to them.' },
        { text: 'Keeping their login credentials confidential.', strong: true },
        { text: 'Not sharing their password or account with another person.', strong: true },
        { text: 'Logging out when they are finished using the system.' },
        { text: 'Immediately reporting suspected unauthorized access or account activity.' },
      ],
    },
    {
      heading: '3. Proper Use of the System',
      paragraphs: [
        'Users must use the system only for authorized hospital and queue-management activities.',
        'Users must not:',
      ],
      list: [
        { text: 'Access information or features they are not authorized to use.' },
        { text: "Use another person's account." },
        { text: 'Attempt to bypass system security or access restrictions.' },
        { text: 'Modify, delete, or manipulate queue records without authorization.' },
        { text: 'Use the system for purposes unrelated to its intended function.' },
        { text: 'Intentionally interfere with the operation or availability of the system.' },
      ],
    },
    {
      heading: '4. Queue and Transaction Information',
      paragraphs: [
        'Queue numbers and transaction information generated by the system are used to support queue management and service operations.',
        'Users should ensure that information entered or managed through the system is accurate and appropriate for its intended purpose.',
      ],
    },
    {
      heading: '5. Personal Information',
      paragraphs: [
        'The system may process personal information necessary for account management and queue-related operations.',
      ],
      strongParagraphs: [
        'Personal information should only be collected, accessed, and processed for legitimate and authorized purposes.',
        'The processing of personal information must follow applicable data privacy laws and organizational policies, including the Data Privacy Act of 2012 (Republic Act No. 10173) and its applicable rules and regulations. The National Privacy Commission identifies transparency, legitimate purpose, and proportionality as core principles for processing personal information.',
      ],
      footer:
        'For more information about how personal information is handled, please refer to the Privacy Policy.',
    },
    {
      heading: '6. Account Security',
      paragraphs: [
        'Users are responsible for maintaining the security of their account credentials. The system may require users to change temporary passwords or reset passwords when necessary.',
        'If a user suspects that their account has been compromised, they should report the issue to the designated system administrator or authorized SWUMed personnel.',
      ],
    },
    {
      heading: '7. System Availability',
      paragraphs: [
        'The SWUMed Queue Management System is intended to support hospital queue operations. However, temporary interruptions may occur because of maintenance, technical problems, network issues, hardware problems, or other circumstances.',
        'Authorized personnel may perform maintenance or system updates when necessary.',
      ],
    },
    {
      heading: '8. Administrative Controls',
      paragraphs: [
        'Authorized administrators may manage system users, roles, positions, kiosks, departments, terminals, queues, and other system configurations according to their assigned permissions.',
      ],
      strongParagraphs: [
        'Administrative actions should only be performed by authorized personnel and for legitimate operational purposes.',
      ],
    },
    {
      heading: '9. Changes to the System',
      paragraphs: [
        "SWUMed may update, modify, or improve the system's features and functionality when necessary to support hospital operations, security, or system requirements.",
        'Changes to these Terms & Conditions may also be made when necessary. The updated version will indicate the applicable Last Updated date.',
      ],
    },
    {
      heading: '10. Acceptance of These Terms',
      strongParagraphs: [
        'By accessing and using the SWUMed Queue Management System, you acknowledge that you have read and understood these Terms & Conditions and agree to comply with the applicable system rules, security requirements, and organizational policies.',
        'If you do not agree with these Terms & Conditions, do not use the system and contact the designated system administrator.',
      ],
    },
  ],
};

const PRIVACY = {
  title: 'Privacy Policy',
  intro:
    'The SWUMed Queuing System respects the privacy of patients, staff, and other users who use the system. This Privacy Policy explains what information may be collected, how it is used, how it is protected, and the rights of users regarding their personal information.',
  sections: [
    {
      heading: '1. Information We Collect',
      paragraphs: [
        'The SWUMed Queuing System may collect and process information necessary to provide and manage queuing services, including:',
      ],
      list: [
        { text: 'Queue number and queue type' },
        { text: 'Selected hospital service or department' },
        { text: 'Priority status, when applicable' },
        { text: 'Date and time of queue registration' },
        { text: 'Transaction or queue status' },
        { text: 'Terminal and service information' },
        { text: 'Information provided by authorized staff when required for queue management' },
      ],
      strongParagraphs: [
        'IMPORTANT: The system only collects information that is necessary for its intended operation and purposes.',
      ],
    },
    {
      heading: '2. How We Use Your Information',
      paragraphs: ['Information collected through the system may be used to:'],
      list: [
        { text: 'Generate and manage queue numbers' },
        { text: 'Organize patients according to their selected service and priority' },
        { text: 'Display queue information on authorized screens' },
        { text: 'Notify or assist patients regarding their queue status' },
        { text: 'Help hospital staff manage daily queues and transactions' },
        { text: 'Generate operational reports and statistics' },
        { text: 'Monitor system performance and improve queuing services' },
        { text: 'Maintain the security and proper operation of the system' },
      ],
    },
    {
      heading: '3. Display of Queue Information',
      paragraphs: [
        'Queue information may be displayed on authorized patient-facing screens, such as queue displays and hospital TV screens.',
        'Only information necessary for identifying and managing the queue should be displayed.',
      ],
      strongParagraphs: [
        'Sensitive personal information should not be publicly displayed through the queuing system.',
      ],
    },
    {
      heading: '4. Data Sharing and Access',
      paragraphs: [
        'Access to information is limited to authorized users based on their assigned roles.',
        'Different system roles may have different levels of access. Hospital administrators, terminals, and system administrators may access information necessary for their responsibilities.',
      ],
      strongParagraphs: [
        'Personal information will not be shared with unauthorized individuals or organizations unless required for legitimate operational, legal, or regulatory purposes.',
      ],
    },
    {
      heading: '5. Data Security',
      paragraphs: [
        'Reasonable security measures are implemented to protect information from unauthorized access, alteration, disclosure, loss, or misuse.',
        'Access to the system may be controlled through authentication, role-based permissions, and other appropriate security measures.',
      ],
      strongParagraphs: [
        'However, no electronic system can guarantee complete security. Users are encouraged to keep their account credentials confidential and to log out after using the system.',
      ],
    },
    {
      heading: '6. Data Retention',
      paragraphs: [
        'Queue and transaction information may be retained for as long as necessary for legitimate hospital operations, reporting, auditing, system management, and other lawful purposes.',
        'Information that is no longer necessary may be deleted, archived, or securely disposed of according to applicable policies and requirements.',
      ],
    },
    {
      heading: '7. Patient Privacy',
      strongParagraphs: [
        'Patients are encouraged to avoid entering unnecessary personal or sensitive information in the queuing system.',
      ],
      paragraphs: [
        "The queuing system is primarily intended for queue management and is not intended to replace the hospital's official patient records or other healthcare information systems.",
      ],
    },
    {
      heading: '8. User Rights',
      paragraphs: [
        'Subject to applicable laws and regulations, users may have rights regarding their personal information, including the right to:',
      ],
      list: [
        { text: 'Be informed about how their information is processed' },
        { text: 'Request access to their personal information' },
        { text: 'Request correction of inaccurate information' },
        { text: 'Request deletion or restriction of information when applicable' },
        { text: 'Raise concerns regarding the handling of their information' },
      ],
      footer:
        'Requests may be subject to identity verification and applicable legal or institutional requirements.',
    },
    {
      heading: '9. Cookies and Technical Information',
      paragraphs: [
        'The system may use technical information, such as session data, device information, or system logs, when necessary to maintain security, authentication, and system functionality.',
        'These technologies are used to support the operation and security of the system and are not intended to collect unnecessary personal information.',
      ],
    },
    {
      heading: '10. Changes to This Privacy Policy',
      paragraphs: [
        'This Privacy Policy may be updated when necessary to reflect changes in the system, hospital procedures, security practices, or applicable requirements.',
      ],
      strongParagraphs: [
        'Users will be informed of significant changes through appropriate channels.',
      ],
    },
    {
      heading: '11. Contact Us',
      paragraphs: [
        'If you have questions, concerns, or requests regarding this Privacy Policy or the handling of your information, please contact the appropriate SWUMed administration or authorized data privacy personnel.',
        'SWUMed Queuing System',
        'Southwestern University PHINMA Medical Center',
        'Cebu City, Philippines',
      ],
      strongParagraphs: [
        'By using the SWUMed Queuing System, you acknowledge that you have read and understood this Privacy Policy and that your information may be processed as described above, subject to applicable laws, regulations, and institutional policies.',
      ],
    },
  ],
};

const DOCUMENTS = { terms: TERMS, privacy: PRIVACY };

export default function LegalModal({ document: initial = 'terms', onClose }) {
  const [current, setCurrent] = useState(
    DOCUMENTS[initial] ? initial : 'terms'
  );

  const doc = DOCUMENTS[current];

  useEffect(() => {
    function handleKey(event) {
      if (event.key === 'Escape') onClose?.();
    }

    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [onClose]);

  return (
    <div className="swu-enter-fade fixed inset-0 z-[110] flex items-start justify-center overflow-y-auto bg-slate-900/50 px-4 py-6">
      <div className="swu-pop relative w-full max-w-3xl rounded-2xl bg-white p-8 shadow-2xl sm:p-10">

        <button
          type="button"
          onClick={onClose}
          aria-label="Close"
          className="swu-press absolute right-5 top-5 rounded-full border border-[#E5E7EB] p-1.5 text-[#4B5563] transition-colors hover:border-[#F0DADA] hover:bg-[#FBF1F1] hover:text-[#9D0A0E]"
        >
          <X size={16} />
        </button>

        <h1 className="text-lg font-bold text-[#1F2937]">{doc.title}</h1>

        <p className="mt-0.5 text-xs text-[#9CA3AF]">
          Last Updated: {LAST_UPDATED}
        </p>

        <p className="mt-3 text-xs leading-6 text-[#4B5563]">{doc.intro}</p>

        <div className="mt-5 space-y-5">
          {doc.sections.map((section) => (
            <section key={section.heading}>
              <h2 className="text-xs font-bold text-[#1F2937]">
                {section.heading}
              </h2>

              {section.paragraphs?.map((text) => (
                <p key={text} className="mt-1.5 text-xs leading-6 text-[#4B5563]">
                  {text}
                </p>
              ))}

              {section.list && (
                <ul className="mt-1.5 space-y-1 pl-4">
                  {section.list.map((item) => (
                    <li
                      key={item.text}
                      className={`list-disc text-xs leading-6 ${
                        item.strong
                          ? 'font-semibold text-[#9D0A0E]'
                          : 'text-[#4B5563]'
                      }`}
                    >
                      {item.text}
                    </li>
                  ))}
                </ul>
              )}

              {section.strongParagraphs?.map((text) => (
                <p
                  key={text}
                  className="mt-1.5 text-xs font-medium leading-6 text-[#9D0A0E]"
                >
                  {text}
                </p>
              ))}

              {section.footer && (
                <p className="mt-1.5 text-xs leading-6 text-[#4B5563]">
                  {section.footer}
                </p>
              )}
            </section>
          ))}
        </div>

        <div className="mt-8 border-t border-[#E5E7EB] pt-4 text-center text-xs">
          <button
            type="button"
            onClick={() => setCurrent('terms')}
            className={`transition-colors hover:underline ${
              current === 'terms'
                ? 'font-bold text-[#9D0A0E]'
                : 'text-[#4B5563] hover:text-[#9D0A0E]'
            }`}
          >
            Terms and Condition
          </button>

          <span className="mx-2 text-[#9CA3AF]">|</span>

          <button
            type="button"
            onClick={() => setCurrent('privacy')}
            className={`transition-colors hover:underline ${
              current === 'privacy'
                ? 'font-bold text-[#9D0A0E]'
                : 'text-[#4B5563] hover:text-[#9D0A0E]'
            }`}
          >
            Privacy Policy
          </button>
        </div>

      </div>
    </div>
  );
}
